language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install luacov
  - luarocks install luaunit
  - luarocks install luafilesystem
  - luarocks install mach

script:
  - cd tests
  - ./run-tests.sh
